### ISSUE TITLE
Fix rep spacing for console

### ISSUE THREAD

**Issue by nchevobbe** [firefox-devtools/original-console-fork#260] opened 2016-09-03 20:42 UTC
When running `npm test` there are 2 errors : 

```
  1) ConsoleAPICall component: console.assert renders:
     Error: Expected 'Assertion failed: Object  { message: "foobar" }' to be 'Assertion failed: Object { message: "foobar" }'
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toBe (node_modules/expect/lib/Expectation.js:66:28)
      at Context.<anonymous> (new-console-output/test/components/console-api-call.test.js:59:52)
```

```
  2) EvaluationResult component: renders a grip result:
     Error: Expected 'Date 1970-01-01T00:00:00.000Z' to be 'Date1970-01-01T00:00:00.000Z'
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toBe (node_modules/expect/lib/Expectation.js:66:28)
      at Context.<anonymous> (new-console-output/test/components/evaluation-result.test.js:23:37)
```

**Comment by linclark** [comment] 2016-09-05 07:33
Ah, this is because of a [patch that landed](https://bugzilla.mozilla.org/show_bug.cgi?id=1284839) to fix spacing between the rep title and properties.

I would expect the second to fail. We want to have a space between the word "Date" and the actual date. I wouldn't expect the first to fail though. I'll have to look into that.

For now, I'll put up a PR that fixes the tests.

**Comment by linclark** [comment] 2016-09-05 07:43
I looked into it. The problem is that some reps were already handling spaces between the title and rest of the rep. The patch added a space in the case of a linked title but not a regular title. We only test regular titles explicitly in the rep tests. That's why the tests didn't fail when there were two spaces.

**Comment by linclark** [comment] 2016-09-05 08:55
This will land in m-c in [Bug 1300494](https://bugzilla.mozilla.org/show_bug.cgi?id=1300494)

**Closed as completed** 2016-09-05 09:53 UTC
