### ISSUE TITLE
Support for server side logging

### ISSUE THREAD

**Issue by janodvarko** [firefox-devtools/original-console-fork#334] opened 2016-09-30 11:49 UTC
One of the features we ported from Firebug to DevTools (to make Firebug users migration simpler) is 'Server Side Logging'
https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Console_messages#Server

The new Console front-end is currently missing the "Server" filter that enables this feature on the client.

Honza

**Comment by linclark** [comment] 2016-09-30 12:16
Thanks for filing. I'm going to mark it as a duplicate of #199, since we don't yet listen for the Server log calls. When we do, we could add the filter at that point.

**Closed as completed by linclark** 2016-09-30 12:16 UTC
